# Generated by Django 3.2.9 on 2022-05-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220315_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='input',
            field=models.TextField(null=True),
        ),
    ]
