# Generated by Django 3.2.9 on 2022-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_solution_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
