# Generated by Django 3.2.9 on 2022-05-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_password',
            field=models.CharField(default='admin123', max_length=20),
        ),
    ]
